### ISSUE TITLE
Small errors in your locale

### ISSUE THREAD

**Issue by chameleon-tbn** [YEWl/feedbro-locale#1]
Hi YEWI,

As Nodetics informed me in the JSON locale file there should be following stuff:

"locale_author_name": "**YEWI**",
"locale_author_email": "**your own email adress**",

And the "locale_source_url": must point to the RAW file otherwise updates bring up an error. So in your case: "**https://raw.githubusercontent.com/YEWl/feedbro-locale/master/feedbro-locale-zh_CN.json**"

kind regards,
 the bugfix

**Comment by 2220209876** [comment]
> Hi YEWI,
> 
> As Nodetics informed me in the JSON locale file there should be following stuff:
> 
> "locale_author_name": "**YEWI**",
> "locale_author_email": "**your own email adress**",
> 
> And the "locale_source_url": must point to the RAW file otherwise updates bring up an error. So in your case: "**https://raw.githubusercontent.com/YEWl/feedbro-locale/master/feedbro-locale-zh_CN.json**"
> 
> kind regards,
> the bugfix

Already fixed, thanks for feedback.
