### ISSUE TITLE
About: Source code package of the chrome extension

### ISSUE THREAD

**Issue by dddaiwstep** [YEWl/feedbro-locale#14]
May i have the source code package of the chrome extension for learning purpose? 
I want to build a same extension before but in vain, you are so profeesional to create this, i want to learn from the source .

Thank you so much.

**Comment by nkh0472** [comment]
> May i have the source code package of the chrome extension for learning purpose?

We are not the developers of Feedbro and do not have access to its source code. Our role is limited to translating the GUI strings provided by the extension's template.

Please reach out to the developer at nodetics@gmail.com for the source code.
