### ISSUE TITLE
一个翻译错误

### ISSUE THREAD

**Issue by umm233** [YEWl/feedbro-locale#3]
在模板文件中：
"mainmenu_error_duplicate_folder": "You have already subscribed to '{1}' in folder '{2}' with the title '{3}'"
但翻译文件中是：
"mainmenu_error_duplicate_folder": "您已经订阅了名为 '{3}' 的文件夹 '{2}' 中的 '{1}' ",
应该是：
"mainmenu_error_duplicate_folder": "您已经订阅了名为 '{3}' 在文件夹 '{2}' 中的 '{1}' ",

**Comment by 2220209876** [comment]
感谢提醒，改为 
"您已经订阅了名为 '{3}' 的文件夹 在'{2}' 中的 '{1}' ",
或许更合适？

**Comment by umm233** [comment]
实际上订阅的不是文件夹，而是说订阅源已存在于某文件夹内，这样翻译会造成一些困扰
