### ISSUE TITLE
一个翻译建议

### ISSUE THREAD

**Issue by toukoubun** [YEWl/feedbro-locale#4]
在添加规则的界面，“匹配”里的第三个选项，英文叫 `None of the conditions` ，意思类似于“没有匹配到下列的规则”
单纯一个`无条件` ，结合边上 `匹配` 的话乍一看会感觉有 无条件匹配的意思？（无条件投降里的无条件的意思）
建议改成 `未匹配到条件` 

<img width="797" alt="qy93Octgvs" src="https://user-images.githubusercontent.com/52944472/87413176-e9a07f80-c604-11ea-81dd-4faba4ad0ba8.png">

**Comment by 2220209876** [comment]
所有条件
任何条件
没有条件
怎么样呢？

**Comment by toukoubun** [comment]
Oh, 我居然忘了确认邮件，不好意思
我觉得可能还是 `未匹配到任何条件` 会比较好懂点，但 `没有条件` 似乎也行，更加工整点

**Comment by Han2L** [comment]
`空`即可

**Comment by nkh0472** [comment]
关于上述建议，我在#7 进行了更新

涉及到本issue界面的内容见
https://github.com/nkh0472/feedbro-locale/blob/8091e32be9d3d092bfbfe28c9b2e22baf0b0495c/feedbro-locale-zh_CN.json#L372-L387

可以使用链接
https://github.com/YEWl/feedbro-locale/raw/8091e32be9d3d092bfbfe28c9b2e22baf0b0495c/feedbro-locale-zh_CN.json
载入我提到的翻译更新。
